# Generated by Django 6.0.4 on 2026-04-15 23:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0003_remove_agendamento_concluido_agendamento_status_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='agendamento',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='data_hora_fim',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servico',
            name='barbeiro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meus_servicos', to=settings.AUTH_USER_MODEL),
        ),
    ]
